### ISSUE TITLE
Issues with supplying the path to the repo

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/diagnostics#1]
In testing, I copy/pasted the actual path to my repo:

/home/mholmes/WorkData/French/Claire_data/mariage_5/svnrepo/exist_db/mariage/anthology

and it was rejected because it had no protocol. Then I tried to browse to it, but since there is no file in the root directory -- they're all in subdirectories -- there was nothing I could select. We need to find a simpler approach here.

**Comment by joeytakeda** [comment]
The problem here is in Oxygen's "ask" editor variable. The only type that allows for browsing files is the "URL" or "relative_url" types, which has the problems that you've described. We could switch the "ask" expected type to "general" but then users would be forced to paste in the full path to the directory and not be able to browse--is that something we want?

**Comment by martindholmes** [comment]
I think the simplest approach is to "ask" for a file, not a directory. In most cases, people will have a file in their root directory. So we'd say: "Please choose any file in the root directory of your project."

**Comment by joeytakeda** [comment]
What do we do in the case where projects don't have a file in the root directory of their project? Is that worth accommodating/thinking about or is it too rare of a case?

**Comment by martindholmes** [comment]
I'm not sure. It seems mad to ask people to create a nonce file, so they can select it, so we can discard it after getting its folder path. :-)

**Comment by joeytakeda** [comment]
Are Oxygen's editor variables the right way to do this? Not only is it annoying to try and work around the file selector for a path to a directory, it also isn't that friendly for using the build by the command line (which I don't think is unreasonable to try to accommodate). But maybe I'm just complicating things!

Edit: What about having a space users to fill in the path to the directory in the instructions document? (We would lose the convenience of a drop down menu, however.)

**Comment by martindholmes** [comment]
Well, for Oxygen users there has to be a way for them to supply the path. For command-line users, we can assume they're going to be able to supply it themselves.

**Comment by martindholmes** [comment]
Sorry @joeytakeda , I don't think I was responding to your last edit. I worry that most users will need to browse to their folder, though. It's surprising how many people really don't know the architecture of their drive, and OSes like Windows seem to go out of their way to obscure the real structure; if you ask a lot of people for the full path to their project folder, they just won't know. They know how to find it, but not where it is.

**Comment by martindholmes** [comment]
Sorry @joeytakeda , I don't think I was responding to your last edit. I worry that most users will need to browse to their folder, though. It's surprising how many people really don't know the architecture of their drive, and OSes like Windows seem to go out of their way to obscure the real structure; if you ask a lot of people for the full path to their project folder, they just won't know. They know how to find it, but not where it is.

**Comment by martindholmes** [comment]
We might be able to wrangle Radu's suggestion here:

https://www.oxygenxml.com/forum/post41917.html#p41894

into a usage of JFileChooser:

http://www.java2s.com/Code/Java/Swing-JFC/SelectadirectorywithaJFileChooser.htm

to get a pure folder-selection dialog.

**Comment by martindholmes** [comment]
I have it working in commit f8bfc8d. Now figuring out how best to integrate it into the process.

**Comment by martindholmes** [comment]
I think it's working now. I want to reorganize the build process a bit more so that if the user cancels out of the dialog, the build doesn't "fail", it just exits gracefully.

**Comment by martindholmes** [comment]
Curses, it fails in Windows at the command line. Doesn't know from "javax". It works fine in Oxygen on Windows though. More investigation to be done. Looks like this depends on the JDK being installed, not just the JRE...

**Comment by martindholmes** [comment]
It's rather odd. From the errors I'm getting (with org.mozilla prefixes), it's as if the JDK 1.8 that's on the Windows machine is still using Rhino rather than Nashorn. But I don't see any way around this, so I think we'll have to detect Windows and use an input box for that instead of the Java dialog box. Oh well.

**Comment by joeytakeda** [comment]
I think the way to do this would to first create an empty property user.dir, which can be set via command line (or in ANT XML file). 

If user.dir='', then check:
- if the OS isn't windows, then do the Java open solution 
- if the OS is windows, then do something else (perhaps fail and open up the instructions document on how to input your directory path in build.xml/how to run this from command line?)

**Comment by martindholmes** [comment]
That sounds exactly right.

**Comment by joeytakeda** [comment]
Partial fix in commit 4a8e217e9da232568fa0ce73d73d33fcee99799c. Ant task now accepts -DprojectDirectory=absolute/or/relative/path/to/dir. But it still isn't failing on Windows gracefully yet.

**Comment by martindholmes** [comment]
This screws up the popup dialog in Oxygen, even on Linux. We need a more carefully-thought-out sequence of events, and it has to be different depending on whether we're running in Oxygen or not:

If NOT Oxygen:
1. Check for path supplied as a parameter. If it's there, continue.
2. If it's not there, branch by OS:
    If Windows, show error message and quit.
    If other OS, show Java dialog to let the user select the folder.

If Oxygen:
1. Branch by OS:
    If Windows, use Oxygen's ${ask} to get the folder.
    If other OS, use the Java dialog.

I'm not sure how feasible this is. In the second case, branching by OS has to happen before the ${ask} variable is used. I can't see how to do that at the moment.

**Comment by martindholmes** [comment]
I don't really understand what you were doing in commit 4a8e217, but it seems to have broken the whole process. Could we just revert it and make a proper plan?

**Comment by joeytakeda** [comment]
It didn't break on my machine whatsoever, in Oxygen or at the command line. But yes, reverting is fine.

**Comment by martindholmes** [comment]
Open the instructions.html file and hit the red triangle. It just breaks.

**Comment by martindholmes** [comment]
I believe this is now fixed.
