### ISSUE TITLE
Directory selector only sometimes working

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/diagnostics#11]
The directory selector usually works, but sometimes will not deploy. Java will open, but the pop-up window doesn't come up. This usually happens if I'm running against the /test/ directory in fairly quick succession. Might be a non-issue for regular users. 

Suggestion: could we have a switch. If ${projectDir} is set at the command line, use that. Otherwise, use the directory selector.

**Comment by martindholmes** [comment]
We definitely need a switch, because the directory browser will not work on Windows anyway.

**Comment by joeytakeda** [comment]
Duplicate of #1 ; closing.
