### ISSUE TITLE
Bug in Windows with new regex-based approach

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/diagnostics#12]
Just tested this in Windows/Oxygen, processing the test folder, and got this:

~~~~~
     [java] Checking corpus.xml (1/3)
     [java] Error at char 42 in xsl:variable/@select on line 1037 column 145 of diagnostics_master_regex.xsl:
     [java]   FORX0002: Syntax error at char 9 in regular expression: Escape character 'U' not allowed
     [java] Syntax error at char 9 in regular expression: Escape character 'U' not allowed
     [java] Java Result: 2
~~~~~

Looking into it now.

**Comment by martindholmes** [comment]
@joeytakeda I think if you document exactly what you're doing in the hcmc:makeRegex() function (where do these instances of '/./' come from, for instance?) we'll be able to get a handle on that. We should also add a test module that enables us to spit out the huge regexes into text files so we can look at them. That might not help in this case, though; it seems to be something in the Windows paths that are input to the replace() operation that triggers the error.

**Comment by joeytakeda** [comment]
This was something I was going to ask you about. I can definitely document the Regex, but the replacement of '/\./' is only needed in the case of diagnostics/test, which produces this path in Java/ANT: 

path/to/diagnostics/./test

Saxon doesn't, though, giving the canonical URI

Path/to/diagnostics/test

So the /\./ is a workaround to something that probably can be fixed in ANT rather than XSLT.

**Comment by martindholmes** [comment]
Hmm. I'm almost certain there's a bug here that's triggered by the fact that you may need to double-escape some regex components in the context of an XPath string, because an XPath string itself has an escape system. It would make sense if this triggered an issue on Windows because of the backslashes in Windows paths.

**Comment by joeytakeda** [comment]
This makes sense to me. 

I'll add a replace for '\' to '\\' to the regex function and clean things up a bit in terms of documentation and regexes on Friday. I don't have anything Windows, but we can test at HCMC.

**Comment by martindholmes** [comment]
This suggests that we should have a separate module for functions, and a test module whose job is to test them; then we could push in some Windows paths as part of the test and watch what happens. Better than trying to find a Windows VM to debug on (although we have to do that too, of course).

**Comment by joeytakeda** [comment]
The '/\./' replace is now gone in last commit. 
I've made it so the build can either take a command line parameter or use the Java option, both of which get passed through <dirname>, which returns the absolute path.

**Comment by martindholmes** [comment]
That replace still seems to be there:

https://github.com/projectEndings/diagnostics/blob/master/xsl/diagnostics_master_regex.xsl#L1042

Did you forget to push?

**Comment by joeytakeda** [comment]
Ah, must have missed one! There were a few. Will fix.

**Comment by martindholmes** [comment]
Update: The entire process is currently broken on Windows. Running in Oxygen against the test folder data finds no errors at all. This should be our priority bug.

**Comment by martindholmes** [comment]
As of commit #4f168c3 everything seems to be working on Windows. We'll need to do more testing and keep an eye on this, though. Working with a Windows 10 VM.
