### ISSUE TITLE
Undefined prefixDefs are not being caught

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/diagnostics#15]
I ran the diagnostics process against the generated ISE-TEI to get a list of elements and attributes and, to my surprise, it passed the diagnostics, even though it is full of references to iseperson: and sp:, which are undefined. Undefined prefixes should be caught as a bad pointer, I think, and displayed with a note in parentheses that says "The prefixDef 'blah' isn't defined".

**Comment by martindholmes** [comment]
Ah -- a problem: can we assume that a private URI scheme must be defined 
as a prefixDef? Can we tell the difference between known public URI 
scheme prefixes and private ones?

**Comment by joeytakeda** [comment]
As discussed on May 29, we decided that we will alter our prefixDef resolution code to do the following:

1. Check to see if the prefix is defined in the document (which we already do)
2. Check to see if the prefix is defined elsewhere in the document (which we already do)
3. Check to see if the prefix is defined in the list of URI schemes (here: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)
 * If it is in this list, then assume the pointer is correct
 * If no, then flag it as an undeclared prefix

**Comment by joeytakeda** [comment]
Should be fixed in commit b1e806f7cc7b1374256a7cc1b0347905ac53f73f.
