### ISSUE TITLE
Add check for @mimeType

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/diagnostics#19]
According to the TEI Guidelines for `att.internetMedia` (whose only attribute is `@mimeType`):

>This attribute class provides an attribute for describing a computer resource, typically available over the internet, using a value taken from a standard taxonomy. At present only a single taxonomy is supported, the Multipurpose Internet Mail Extensions (MIME) Media Type system. This typology of media types is defined by the Internet Engineering Task Force in RFC 2046. The list of types is maintained by the Internet Assigned Numbers Authority (IANA). The mimeType attribute must have a value taken from this list.

That list of types is here: https://www.iana.org/assignments/media-types/media-types.xhtml and, in XML here: https://www.iana.org/assignments/media-types/media-types.xml

We should process the XML version, create a RegEx for it, and then add a check to make sure that all `@mimeType` attributes come from this list.

**Comment by martindholmes** [comment]
Good idea. We'll need an automated process for downloading the sources and regenerating the list, because of course it changes regularly.

**Comment by joeytakeda** [comment]
We'll have to remember that there's also the character encoding stuff in there as well:

```
<ref mimeType="application/tei+xml; charset=UTF-8"
 target="http://sourceforge.net/p/tei/code/HEAD/tree/trunk/P5/Source/guidelines-en.xml"/>
```

**Comment by martindholmes** [comment]
That's a long list too:

http://www.iana.org/assignments/character-sets/character-sets.xhtml

In fact, it's so long, and most of its values are so obsolete or obscure, that I think we might just pick a small subset of common ones, and warn if the charset doesn't match that set.

**Comment by joeytakeda** [comment]
Yes, that's probably the right way to go. Note that these are case insensitive, but that uppercase is more widely accepted: https://stackoverflow.com/questions/3251954/xml-file-encoding-format-utf-8-vs-utf-8. Maybe we should also warn if they have a lowercase value instead of an uppercase?

**Comment by joeytakeda** [comment]
This is now done in commit c1cefa9; closing.
