### ISSUE TITLE
The current checks should include internal idrefs

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/diagnostics#2]
The current checking that's done does not include checking references within a document to xml:ids in the same document. We originally decided to delegate this to schema validation, on the basis that it's normally done by validators. However, on second thoughts, I don't believe we should skip this. idref checking is not provided in RelaxNG, it's only available if DTD compatibility is turned on, so we can't be sure it's covered by normal validation.

**Comment by joeytakeda** [comment]
Sounds like a good idea to me!

**Comment by martindholmes** [comment]
I've added this check in commit #f236078.
