### ISSUE TITLE
What's the readme.txt for?

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/diagnostics#6]
@joeytakeda Do we need README.txt? Isn't README.md enough?

**Comment by joeytakeda** [comment]
I think I originally thought it would make what is now instructions.html. So it's superfluous now.

Should we convert instructions.html to markdown for a wiki page in the build process?

**Comment by martindholmes** [comment]
No, let's keep README.md as the intro to the project (which shows by default on GitHub) and instructions.html as the document that tells you what to do. Doesn't matter if they overlap a bit. I'll get rid of README.txt.

**Comment by martindholmes** [comment]
Gone in commit c7c2fbf.
