### ISSUE TITLE
Can we move the xmlLangRegex to a .txt file?

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/diagnostics#8]
Can we move the xmlLangRegex to a text file? On my system, the large Regex causes oXygen to move at a glacial pace, which makes editing diagnostics_master.xsl difficult.

**Comment by martindholmes** [comment]
That's a good idea. It can be loaded with unparsed-text(). Don't for get to do normalize-space on it. In fact we should probably just strip all whitespace from it, just in case; it doesn't have any whitespace and shouldn't need any.

Add the text file to the repo. Strictly speaking it's generated from the IANA document. but that document presumably doesn't change often enough for us to make this dynamic. Or should we just generate it afresh every time, perhaps?

**Comment by martindholmes** [comment]
Fixed in commit 7dd087a. Testing now.

**Comment by martindholmes** [comment]
All good.
